---
# Per environment values which override defaults in hmpps-cell-sharing-risk-assessment-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: cell-sharing-risk-assessment-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://cell-sharing-risk-assessment-ui-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://template-kotlin-dev.hmpps.service.justice.gov.uk'
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: move-a-prisoner-alerts-nonprod
