---
# Per environment values which override defaults in hmpps-cell-sharing-risk-assessment-ui/values.yaml

generic-service:
  ingress:
    host: cell-sharing-risk-assessment-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://cell-sharing-risk-assessment-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://template-kotlin.hmpps.service.justice.gov.uk'
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: move-a-prisoner-alerts-prod
